"""implement Contact and many to one relationship to Lead

Revision ID: 08a48a35550b
Revises: d7885f113dce
Create Date: 2024-09-18 10:38:36.910495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a48a35550b'
down_revision = 'd7885f113dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['leads.id'], name=op.f('fk_contacts_company_id_leads')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postings', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alumni', sa.Boolean(), nullable=True))
        batch_op.drop_column('contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('alumni')
        batch_op.drop_column('postings')

    op.drop_table('contacts')
    # ### end Alembic commands ###
