"""add note attribute to reminders

Revision ID: 2736c2b72750
Revises: 7f2e023ed6e1
Create Date: 2024-09-19 14:24:15.168126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2736c2b72750'
down_revision = '7f2e023ed6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
