"""end of 8/9 work

Revision ID: 68371715d658
Revises: 7113881d2a14
Create Date: 2024-10-09 12:43:00.648845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68371715d658'
down_revision = '7113881d2a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pokemon', sa.VARCHAR(), nullable=True),
    sa.Column('pokemon_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
