"""end of 8/9 work

Revision ID: 7113881d2a14
Revises: e305c9bd66ae
Create Date: 2024-10-09 12:41:02.016534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7113881d2a14'
down_revision = 'e305c9bd66ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon', sa.String(), nullable=True),
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###
