"""add pokemon teams table

Revision ID: 9ba0409df3ee
Revises: 08f54acfd5a9
Create Date: 2024-10-08 09:38:07.721171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba0409df3ee'
down_revision = '08f54acfd5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('pokemon_1', sa.String(), nullable=True),
    sa.Column('pokemon_2', sa.String(), nullable=True),
    sa.Column('pokemon_3', sa.String(), nullable=True),
    sa.Column('pokemon_4', sa.String(), nullable=True),
    sa.Column('pokemon_5', sa.String(), nullable=True),
    sa.Column('pokemon_6', sa.String(), nullable=True),
    sa.Column('analysis', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_teams')
    # ### end Alembic commands ###
