"""incorporate pokemon storage for id reference

Revision ID: e305c9bd66ae
Revises: 9ba0409df3ee
Create Date: 2024-10-09 11:30:11.832281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e305c9bd66ae'
down_revision = '9ba0409df3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon', sa.String(), nullable=True),
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###
